
name: Release

on:
  push:
    tags:
      - '**'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - name: Update apt
        run: sudo apt-get update -y
      - name: Install os dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: revelation-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/linux/x64/release/bundle/revelation-${{github.ref_name}}-linux.zip

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter --version
      - run: flutter doctor -v
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Download sqlite3.dll
        run: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/tekartik/sqflite/master/sqflite_common_ffi/lib/src/windows/sqlite3.dll', "build/windows/runner/Release/sqlite3.dll")
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: revelation-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/windows/runner/Release/revelation-${{github.ref_name}}-windows.zip

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter --version
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Install appdmg
        run: npm install -g appdmg
      - name: package dmg
        run: appdmg macos/assets/config.json revelation-${{github.ref_name}}-mac.dmg
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node -v
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: revelation-${{github.ref_name}}-mac.dmg

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter --version
      - run: flutter doctor -v
      - name: Install project dependencies
        run: flutter pub get
      - name: Build artifacts
        run: flutter build apk --release
      - name: Rename
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/revelation-${{github.ref_name}}-android.apk
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/app/outputs/flutter-apk/revelation-${{github.ref_name}}-android.apk

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}